language: php
dist: bionic

php:
    - 7.4

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_script:
    - composer install

script:
    - ./vendor/bin/php-cs-fixer fix --config=.php_cs --diff --verbose --dry-run
    - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage-clover.xml
