version: "2"

networks:
    lan:
        external: false
  # web:
  #     external: true

services:
    php:
        image: 0x12f/php:latest
        environment:
            - DEBUG=0
            - ANALYTICS=0
          # - SALT=Please-Change-Me
          # - DATABASE=mysql://user:secret@localhost/mydb
        volumes:
            - ./app:/var/container/app:ro
            - ./config:/var/container/config:ro
            - ./public:/var/container/public:ro
            - ./src:/var/container/src:ro
            - ./theme:/var/container/theme:ro
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
            - ./vendor:/var/container/vendor:ro
      # labels:
      #     - traefik.enable=false
        networks:
            - lan

    web:
        image: alksily/nginx-push-stream-module:latest
        volumes_from:
            - php
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./var/log/nginx:/var/log/nginx
        ports:
            - 9000:80
      # labels:
      #     - traefik.enable=true
      #     - traefik.port=80
      #     - traefik.backend=demo.site.0x12f.com
      #     - traefik.frontend.rule=Host:demo.site.0x12f.com
      #     - traefik.frontend.redirect.entryPoint=https
      #     - traefik.docker.network=web
        networks:
            - lan
      #     - web

    cache:
        image: redis:4-alpine
        restart: always
      # labels:
      #     - traefik.enable=false
        networks:
            - lan
