version: "3"

services:
    platform:
        image: 0x12f/platform:dev
        environment:
            - DEBUG=1
          # - SALT=Please-Change-Me
          # - SIMPLE_ORDER_SERIAL=1
          # - SIMPLE_PHONE_CHECK=1
          # - DATABASE=mysql://user:secret@localhost/mydb
          # - SENTRY=""
        volumes:
            - ./.php_cs:/var/container/.php_cs:ro
            - ./.composer.json:/var/container/.composer.json:rw
            - ./.composer.lock:/var/container/.composer.lock:rw
            - ./config:/var/container/config:rw
            - ./plugin:/var/container/plugin:rw
            - ./public:/var/container/public:rw
            - ./src:/var/container/src:rw
            - ./theme:/var/container/theme:rw
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
            - ./vendor:/var/container/vendor:ro
            - ./php-cs-fixer.phar:/var/container/php-cs-fixer.phar:ro
        ports:
            - 9000:80
