version: "2"

networks:
    lan:
        external: false

services:
    php:
        image: 0x12f/php:latest
        environment:
            - DEBUG=1
            - ANALYTICS=0
        volumes:
            - $PWD/app:/var/container/app:ro
            - $PWD/config:/var/container/config:ro
            - $PWD/public:/var/container/public:ro
            - $PWD/src:/var/container/src:ro
            - $PWD/theme:/var/container/theme:ro
            - $PWD/var:/var/container/var:rw
            - $PWD/var/upload:/var/container/public/uploads:rw
            - $PWD/vendor:/var/container/vendor:ro
        networks:
            - lan

    web:
        image: alksily/nginx-push-stream-module:latest
        volumes_from:
            - php
        volumes:
            - $PWD/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - $PWD/var/log/nginx:/var/log/nginx
        ports:
            - 9000:80
        networks:
            - lan

    cache:
        image: redis:4-alpine
        restart: always
        networks:
            - lan
