version: "3"

services:
    platform:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: ghcr.io/getwebspace/platform:dev
        environment:
            - TEST=1
            - DEBUG=1
            # - DATABASE=mysql://user:password@hostname/database
            # - SIMPLE_PHONE_CHECK=1
        volumes:
            - ./bin:/var/container/bin:rw
            - ./config:/var/container/config:rw
            - ./plugin:/var/container/plugin:rw
            - ./public:/var/container/public:rw
            - ./src:/var/container/src:rw
            - ./tests:/var/container/tests:rw
            - ./theme:/var/container/theme:rw
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
            - ./.php-cs-fixer.dist.php:/var/container/.php-cs-fixer.dist.php:ro
            - ./composer.json:/var/container/composer.json:rw
            - ./composer.lock:/var/container/composer.lock:rw
            - ./phpunit.xml:/var/container/phpunit.xml:rw
            - ./migrations.json:/var/container/migrations.json:rw
        ports:
            - 9000:80
