version: "3"

services:
    platform:
        build:
            context: .
            dockerfile: docker/debian/Dockerfile
        image: 0x12f/platform:test
        environment:
            - DEBUG=0
        volumes:
            - ./config:/var/container/config:rw
            - ./plugin:/var/container/plugin:rw
            - ./public:/var/container/public:rw
            - ./src:/var/container/src:rw
            - ./tests:/var/container/tests:rw
            - ./theme:/var/container/theme:rw
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
            - ./vendor:/var/container/vendor:ro
            - ./.php_cs.dist:/var/container/.php_cs.dist:ro
            - ./composer.json:/var/container/composer.json:rw
            - ./composer.lock:/var/container/composer.lock:rw
            - ./phpunit.xml:/var/container/phpunit.xml:ro
