version: "3"

services:
    platform:
        build:
            context: .
            dockerfile: docker/debian/Dockerfile
        image: 0x12f/platform:dev
        environment:
            - DEBUG=1
          # - SALT=Please-Change-Me
          # - SIMPLE_PHONE_CHECK=1
          # - DATABASE=mysql://user:secret@localhost/mydb
        volumes:
            - ./bin:/var/container/bin:ro
            - ./config:/var/container/config:ro
            - ./plugin:/var/container/plugin:rw
            - ./public:/var/container/public:rw
            - ./src:/var/container/src:ro
            - ./tests:/var/container/tests:ro
            - ./theme:/var/container/theme:rw
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
            - ./vendor:/var/container/vendor:rw
            - ./.php-cs-fixer.dist.php:/var/container/.php-cs-fixer.dist.php:ro
            - ./migrations.json:/var/container/migrations.json:ro
            - ./composer.json:/var/container/composer.json:rw
            - ./composer.lock:/var/container/composer.lock:rw
            - ./phpunit.xml:/var/container/phpunit.xml:ro
        ports:
            - 9000:80
