version: "3"

services:
    platform:
        image: 0x12f/platform:dev
        environment:
            - DEBUG=1
          # - SALT=Please-Change-Me
          # - SIMPLE_PHONE_CHECK=1
          # - DATABASE=mysql://user:secret@localhost/mydb
          # - SENTRY=""
        volumes:
            - ./config:/var/container/config:ro
            - ./plugin:/var/container/plugin:rw
            - ./public:/var/container/public:ro
            - ./src:/var/container/src:ro
            - ./theme:/var/container/theme:rw
            - ./var:/var/container/var:rw
            - ./var/upload:/var/container/public/uploads:rw
            - ./vendor:/var/container/vendor:ro
        ports:
            - 9000:80
