name: Docker builder

on:
    push:
        tags:
            - '*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    # build platform
    debian:
        runs-on: ubuntu-latest
        name: Build base container
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v3

            -   name: Set tag name environment variable
                id: setup_env
                run: |
                    echo "NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
                    echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
                    echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

            -   name: Log in to the Container registry
                uses: docker/login-action@v2
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v3
                with:
                    context: .
                    push: true
                    file: docker/Dockerfile
                    tags: |
                        ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup_env.outputs.VERSION }}
                        ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                    build-args: |
                        NO_DEV=--no-dev
                        NAME=${{ steps.setup_env.outputs.NAME }}
                        BRANCH=${{ steps.setup_env.outputs.BRANCH }}
                        VERSION=${{ steps.setup_env.outputs.VERSION }}
                        COMMIT=${{ github.sha }}
