name: Docker builder

on:
    push:
        # Publish `master` as Docker `latest` image.
        branches:
            - master
            - dev

        # Publish `1.2.3` tags as releases.
        tags:
            - '*'

env:
    IMAGE_NAME: 0x12f/platform

jobs:
    # Run tests.
    # See also https://docs.docker.com/docker-hub/builds/automated-testing/
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run tests
              run: |
                  docker-compose --file docker-compose.test.yml build
                  docker-compose exec platform vendor/bin/php-cs-fixer fix --config=.php_cs.dist
                  docker-compose exec platform vendor/bin/phpunit --color=always --configuration phpunit.xml

    # Push image to GitHub Packages.
    # See also https://docs.docker.com/docker-hub/builds/
    push:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'

        steps:
            - uses: actions/checkout@v2

            - name: Log into registry
              run: echo "${{ secrets.DOCKER_HUB }}" | docker login --username ${{ github.actor }} --password-stdin

            - name: Build Debian image and push
              run: |
                  VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
                  [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
                  [ "$VERSION" == "master" ] && VERSION=latest

                  echo IMAGE_ID=$IMAGE_ID
                  echo VERSION=$VERSION

                  docker build . --build-arg=COMMIT=${{ github.sha }} --build-arg=BRANCH=$VERSION --file docker/debian/Dockerfile --tag $IMAGE_NAME:$VERSION
                  docker push $IMAGE_NAME:$VERSION
