name: Docker builder

on:
    push:
        tags:
            - '*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    # Run tests.
    # See also https://docs.docker.com/docker-hub/builds/automated-testing/
    #    test:
    #        runs-on: ubuntu-latest
    #        name: Testing
    #        steps:
    #            -   uses: actions/checkout@v3
    #
    #            -   name: Set up Docker Buildx
    #                uses: docker/setup-buildx-action@v2
    #
    #            -   name: Build test version
    #                run: docker-compose --file docker-compose.test.yml build --build-arg=NO_DEV=""
    #
    #            -   name: Run test PHP_CS
    #                run: docker-compose --file docker-compose.test.yml run phpcs
    #
    #            -   name: Run test PHPUnit
    #                run: docker-compose --file docker-compose.test.yml run phpunit

    # build alpine
    debian:
        #        needs: test
        runs-on: ubuntu-latest
        name: Build base container
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v3

            -   name: Set tag name environment variable
                id: setup_env
                run: |
                    echo "NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
                    echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
                    echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

            -   name: Log in to the Container registry
                uses: docker/login-action@v2
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v3
                with:
                    context: .
                    push: true
                    file: docker/Dockerfile
                    tags: |
                        ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup_env.outputs.VERSION }}
                        ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                    build-args: |
                        NO_DEV=--no-dev
                        VERSION=${{ github.ref }}
                        COMMIT=${{ github.sha }}
